export const ActionTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    API_REQUEST: "API_REQUEST",
    API_SUCCESS: "API_SUCCESS",
    API_FAILURE: "API_FAILURE",
    API_LIST_END: "API_LIST_END",
    FILTERED_ARTICLES: "FILTERED_ARTICLES"

}